apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  strategy: {}
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ms-demo-catalog-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
